# Generated by Django 4.1.5 on 2023-02-15 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chinese_folktales_website', '0004_alter_story_level_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['story_id']},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['level_id']},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['story_id']},
        ),
    ]
