# Generated by Django 4.1.5 on 2023-02-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese_folktales_website', '0005_alter_comment_options_alter_level_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='bg_image',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
