# Generated by Django 4.1.5 on 2023-02-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese_folktales_website', '0007_rename_bg_image_story_audiofile_story_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='textfile',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to='texts/'),
        ),
    ]
