# Generated by Django 4.1.5 on 2023-02-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese_folktales_website', '0008_alter_story_textfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='textfile',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to='stories/'),
        ),
    ]
