# Generated by Django 4.1.5 on 2023-02-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese_folktales_website', '0010_alter_story_audiofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='images',
            field=models.FileField(default=None, max_length=1000, null=True, upload_to='stories/images/'),
        ),
    ]
