# Generated by Django 4.1.5 on 2023-02-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese_folktales_website', '0012_alter_story_audiofile_alter_story_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='audiofile',
            field=models.FileField(max_length=1000, null=True, upload_to='<int:story_id>/stories/audio/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='images',
            field=models.FileField(max_length=1000, null=True, upload_to='<int:story_id>/stories/images/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='textfile',
            field=models.FileField(max_length=1000, null=True, upload_to='<int:story_id>/stories/'),
        ),
    ]
