# Generated by Django 4.1.5 on 2023-02-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese_folktales_website', '0017_alter_story_bg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='audiofile',
            field=models.FileField(upload_to='stories/audio/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='bg_image',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
