# Generated by Django 4.1.5 on 2023-02-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese_folktales_website', '0019_alter_story_audiofile_alter_story_bg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='audiofile',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='story',
            name='bg_image',
            field=models.URLField(max_length=1000),
        ),
    ]
