# Generated by Django 4.1.5 on 2023-03-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese_folktales_website', '0020_alter_story_audiofile_alter_story_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
