# Generated by Django 4.1.5 on 2023-03-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese_folktales_website', '0021_story_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='audio_bg_image',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
