# Generated by Django 4.1.5 on 2023-03-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinese_folktales_website', '0022_story_audio_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='chinese_title',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
