# Generated by Django 4.1.5 on 2023-03-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chinese_folktales_website', '0024_rename_favourite_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='name',
            new_name='level',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
