# Generated by Django 4.1.5 on 2023-03-10 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chinese_folktales_website', '0025_rename_name_level_level_delete_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='level',
            new_name='name',
        ),
    ]
