# Generated by Django 4.1.5 on 2023-03-14 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chinese_folktales_website', '0027_level_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='level',
        ),
    ]
